In [1]:
include("../../src/WaterLily.jl")

Main.WaterLily

In [2]:
optPois = "DebugMultP"
optSour = "Easy"
optBCon = "Neu"

computationID = optPois * "_" * optSour * "_" * optBCon * "_"
print(computationID,"\n")


DebugMultP_Easy_Neu_


In [3]:

T=Float32
N = (2^4,2^4)
D = length(N)
Ng = N .+ 2
Nd = (Ng..., 2)

(18, 18, 2)

In [4]:
offset = -0.3

optSour=="Hard" && (SourceFunc(x,y) = (
    -4 *pi^2 * (1/N[1]^2 + 1/N[2]^2) * sin.(2*pi*(x/N[1].+offset)) .* sin.(2*pi*(y/N[2].+offset)) +
    -16*pi^2 * (1/N[1]^2 + 1/N[2]^2) * sin.(8*pi*(x/N[1].+offset)) .* sin.(8*pi*(y/N[2].+offset))
))

optSour=="Hard" && (ManufacSol(x,y) = (
    sin.(2*pi*(x/N[1].+offset)) .* sin.(2*pi*(y/N[2].+offset)) +
    sin.(8*pi*(x/N[1].+offset)) .* sin.(8*pi*(y/N[2].+offset))/4
))

optSour=="Easy" && (SourceFunc(x,y) = (
    4*pi^2 * (
        cos.(2*pi*(x/N[1])) .* (1 .-cos.(2*pi*(y/N[2])))/N[1]^2 +
        (1 .-cos.(2*pi*(x/N[1]))) .* cos.(2*pi*(y/N[2]))/N[2]^2
    )
))

optSour=="Easy" && (ManufacSol(x,y) = (
    (1 .-cos.(2*pi*(x/N[1]))) .* (1 .-cos.(2*pi*(y/N[2]))) 
))

ManufacSol (generic function with 1 method)

In [5]:
solIni = zeros(Ng)
source = zeros(Ng)
μ₀ = ones(Nd)
# WaterLily.BC!(μ₀,ntuple(zero, D))

# BCPer!(solIni)
# BCPer!(source)
# BCPer!(μ₀)

X = transpose(reshape([i-1.5 for i=1:Ng[1] for j=1:Ng[2]],Ng[2],Ng[1]))
Y = transpose(reshape([j-1.5 for i=1:Ng[1] for j=1:Ng[2]],Ng[2],Ng[1]))

source = SourceFunc(X,Y)
realSol = ManufacSol(X,Y)
originalSource = copy(source)

18×18 Matrix{Float64}:
 0.00581243  0.00581243  0.0279539  …  0.0279539  0.00581243  0.00581243
 0.00581243  0.00581243  0.0279539     0.0279539  0.00581243  0.00581243
 0.0279539   0.0279539   0.043219      0.043219   0.0279539   0.0279539
 0.068866    0.068866    0.0714251     0.0714251  0.068866    0.068866
 0.12232     0.12232     0.108278      0.108278   0.12232     0.12232
 0.180179    0.180179    0.148168   …  0.148168   0.180179    0.180179
 0.233633    0.233633    0.185021      0.185021   0.233633    0.233633
 0.274545    0.274545    0.213227      0.213227   0.274545    0.274545
 0.296686    0.296686    0.228492      0.228492   0.296686    0.296686
 0.296686    0.296686    0.228492      0.228492   0.296686    0.296686
 0.274545    0.274545    0.213227   …  0.213227   0.274545    0.274545
 0.233633    0.233633    0.185021      0.185021   0.233633    0.233633
 0.180179    0.180179    0.148168      0.148168   0.180179    0.180179
 0.12232     0.12232     0.108278      0.108278   

In [6]:
ml = pTest = WaterLily.MultiLevelPoisson(solIni, μ₀, source)

Main.WaterLily.MultiLevelPoisson{Float64, Matrix{Float64}, Array{Float64, 3}}([0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0; … ; 0.0 0.0 … 0.0 0.0; 0.0 0.0 … 0.0 0.0], [1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0; … ; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0;;; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0; … ; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0], [0.005812430292869291 0.005812430292869291 … 0.0058124302928693064 0.005812430292869291; 0.005812430292869291 0.005812430292869291 … 0.0058124302928693064 0.005812430292869291; … ; 0.0058124302928693064 0.0058124302928693064 … 0.005812430292869324 0.0058124302928693064; 0.005812430292869291 0.005812430292869291 … 0.0058124302928693064 0.005812430292869291], Main.WaterLily.Poisson{Float64, Matrix{Float64}, Array{Float64, 3}}[Main.WaterLily.Poisson{Float64, Matrix{Float64}, Array{Float64, 3}}([1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0; … ; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0;;; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0; … ; 1.0 1.0 … 1.0 1.0; 1.0 1.0 … 1.0 1.0], [0.0 0.0 … 0.0 0

In [7]:
p = pTest.levels[1]
WaterLily.residual!(p)

In [8]:
#WaterLily.solver!(pTest)

In [9]:
#display(pTest.x)

In [10]:
l = 1
fine,coarse = ml.levels[l],ml.levels[l+1]
WaterLily.Jacobi!(fine)
WaterLily.restrict!(coarse.r,fine.r)
fill!(coarse.x,0.)
fine, coarse = Nothing, Nothing

(Nothing, Nothing)

In [11]:
l = 2
fine,coarse = ml.levels[l],ml.levels[l+1]
WaterLily.Jacobi!(fine)
WaterLily.restrict!(coarse.r,fine.r)
fill!(coarse.x,0.)
fine, coarse = Nothing, Nothing

(Nothing, Nothing)

In [12]:
l = 3
fine,coarse = ml.levels[l],ml.levels[l+1]
WaterLily.Jacobi!(fine)
WaterLily.restrict!(coarse.r,fine.r)
fill!(coarse.x,0.)
fine, coarse = Nothing, Nothing

(Nothing, Nothing)

In [13]:
# using LinearAlgebra: ⋅
# for i∈2:3, j∈2:3
#     pTest.levels[3].z[i,j] = pTest.levels[3].ϵ[i,j] = pTest.levels[3].r[i,j]*pTest.levels[3].iD[i,j]
# end

# display(pTest.levels[3].x)
# display(pTest.levels[3].r)
# display(pTest.levels[3].ϵ)

# rho = pTest.levels[3].r ⋅ pTest.levels[3].z

# display(rho)

# for i∈2:3, j∈2:3
#     pTest.levels[3].z[i,j] = WaterLily.mult(CartesianIndex(i,j),pTest.levels[3].L,pTest.levels[3].D,pTest.levels[3].ϵ)
# end

# display(pTest.levels[3].z)

# rhop = pTest.levels[3].z⋅pTest.levels[3].ϵ

# display(rhop)
# display(pTest.levels[3].x)
# display(pTest.levels[3].r)
# display(pTest.levels[3].ϵ)
# display(pTest.levels[3].z)
WaterLily.pcg!(pTest.levels[4],it=6)
# display(pTest.levels[3].x)
# display(pTest.levels[3].r)
# display(pTest.levels[3].ϵ)
# display(pTest.levels[3].z)
WaterLily.prolongate!(pTest.levels[3].ϵ,pTest.levels[4].x)
display(pTest.levels[3].x)
display(pTest.levels[3].r)
display(pTest.levels[3].ϵ)
display(pTest.levels[3].z)
WaterLily.increment!(pTest.levels[3])
display(pTest.levels[3].x)
display(pTest.levels[3].r)
display(pTest.levels[3].ϵ)
display(pTest.levels[3].z)

6×6 Matrix{Float64}:
 0.0   0.0        0.0        0.0        0.0       0.0
 0.0  -0.227135  -0.185773  -0.185773  -0.344354  0.0
 0.0  -0.185773   0.979898   0.979898  -0.356096  0.0
 0.0  -0.185773   0.979898   0.979898  -0.356096  0.0
 0.0  -0.344354  -0.356096  -0.356096  -0.589009  0.0
 0.0   0.0        0.0        0.0        0.0       0.0

6×6 Matrix{Float64}:
 0.0   0.0        0.0        0.0         0.0        0.0
 0.0   0.371546  -0.56699   -0.449771    0.541869   0.0
 0.0  -0.56699   -1.58825   -1.41793    -0.279448   0.0
 0.0  -0.449771  -1.41793   -1.2476     -0.0347926  0.0
 0.0   0.541869  -0.279448  -0.0347926   0.712191   0.0
 0.0   0.0        0.0        0.0         0.0        0.0

6×6 Matrix{Float64}:
 0.0  0.0      0.0      0.0      0.0      0.0
 0.0  1.41949  1.41949  1.66363  1.66363  0.0
 0.0  1.41949  1.41949  1.66363  1.66363  0.0
 0.0  1.66363  1.66363  1.96613  1.96613  0.0
 0.0  1.66363  1.66363  1.96613  1.96613  0.0
 0.0  0.0      0.0      0.0      0.0      0.0

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

6×6 Matrix{Float64}:
 0.0  0.0      0.0      0.0      0.0      0.0
 0.0  1.19235  1.23371  1.47786  1.31928  0.0
 0.0  1.23371  2.39939  2.64353  1.30754  0.0
 0.0  1.47786  2.64353  2.94603  1.61004  0.0
 0.0  1.31928  1.30754  1.61004  1.37712  0.0
 0.0  0.0      0.0      0.0      0.0      0.0

6×6 Matrix{Float64}:
 0.0  0.0        0.0        0.0        0.0       0.0
 0.0  3.21052    0.608352   1.45801    2.2055    0.0
 0.0  0.608352  -2.07654   -1.47628   -0.581947  0.0
 0.0  1.45801   -1.47628   -0.642606   0.267706  0.0
 0.0  2.2055    -0.581947   0.267706   0.712191  0.0
 0.0  0.0        0.0        0.0        0.0       0.0

6×6 Matrix{Float64}:
 0.0  0.0      0.0      0.0      0.0      0.0
 0.0  1.41949  1.41949  1.66363  1.66363  0.0
 0.0  1.41949  1.41949  1.66363  1.66363  0.0
 0.0  1.66363  1.66363  1.96613  1.96613  0.0
 0.0  1.66363  1.66363  1.96613  1.96613  0.0
 0.0  0.0      0.0      0.0      0.0      0.0

6×6 Matrix{Float64}:
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0

In [14]:
for i ∈ 1:length(pTest.levels)
    display(pTest.levels[i].r)
end

18×18 Matrix{Float64}:
 0.0  0.0        0.0        0.0        …  0.0        0.0        0.0
 0.0  0.0139769  0.0294743  0.0554248     0.0294743  0.0139769  0.0
 0.0  0.0294743  0.0496895  0.0741293     0.0496895  0.0294743  0.0
 0.0  0.0554248  0.0741293  0.0768787     0.0741293  0.0554248  0.0
 0.0  0.0893307  0.106061   0.0804709     0.106061   0.0893307  0.0
 0.0  0.12603    0.140624   0.0843592  …  0.140624   0.12603    0.0
 0.0  0.159936   0.172556   0.0879515     0.172556   0.159936   0.0
 0.0  0.185887   0.196996   0.0907009     0.196996   0.185887   0.0
 0.0  0.199931   0.210223   0.0921888     0.210223   0.199931   0.0
 0.0  0.199931   0.210223   0.0921888     0.210223   0.199931   0.0
 0.0  0.185887   0.196996   0.0907009  …  0.196996   0.185887   0.0
 0.0  0.159936   0.172556   0.0879515     0.172556   0.159936   0.0
 0.0  0.12603    0.140624   0.0843592     0.140624   0.12603    0.0
 0.0  0.0893307  0.106061   0.0804709     0.106061   0.0893307  0.0
 0.0  0.0554248  0.074129

10×10 Matrix{Float64}:
 0.0  0.0        0.0         0.0        …  0.0        0.0       0.0
 0.0  0.162473   0.251655    0.319637      0.261873   0.189552  0.0
 0.0  0.251655   0.242756    0.0876738     0.269835   0.311801  0.0
 0.0  0.319637   0.0876738  -0.493728      0.137603   0.412802  0.0
 0.0  0.366216  -0.0304352  -0.923129      0.0356512  0.482231  0.0
 0.0  0.366216  -0.0304352  -0.923129   …  0.0356512  0.482231  0.0
 0.0  0.319637   0.0876738  -0.493728      0.137603   0.412802  0.0
 0.0  0.261873   0.269835    0.137603      0.296914   0.332237  0.0
 0.0  0.189552   0.311801    0.412802      0.332237   0.216631  0.0
 0.0  0.0        0.0         0.0           0.0        0.0       0.0

6×6 Matrix{Float64}:
 0.0  0.0        0.0        0.0        0.0       0.0
 0.0  3.21052    0.608352   1.45801    2.2055    0.0
 0.0  0.608352  -2.07654   -1.47628   -0.581947  0.0
 0.0  1.45801   -1.47628   -0.642606   0.267706  0.0
 0.0  2.2055    -0.581947   0.267706   0.712191  0.0
 0.0  0.0        0.0        0.0        0.0       0.0

4×4 Matrix{Float64}:
 0.0   0.0           0.0          0.0
 0.0   8.90379e-17  -8.48942e-18  0.0
 0.0  -8.48942e-18   2.16403e-17  0.0
 0.0   0.0           0.0          0.0

In [ ]:
# l = 2
# fine,coarse = ml.levels[l],ml.levels[l+1]
# WaterLily.smooth!(coarse)
# # correct fine
# WaterLily.prolongate!(fine.ϵ,coarse.x)
# WaterLily.increment!(fine)
# fine, coarse = Nothing, Nothing

In [ ]:
l = 1
fine,coarse = ml.levels[l],ml.levels[l+1]
WaterLily.smooth!(coarse)
# correct fine
WaterLily.prolongate!(fine.ϵ,coarse.x)
WaterLily.increment!(fine)
fine, coarse = Nothing, Nothing

In [ ]:
WaterLily.smooth!(ml.levels[1])

In [ ]:
for i ∈ 1:length(pTest.levels)
    display(pTest.levels[i].ϵ)
end